apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "housewatch.fullname" . }}-worker
  labels:
    {{- include "housewatch.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "housewatch.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/service: worker
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "housewatch.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/service: worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["./bin/celery"]
          env:
          - name: REDIS_URL
            value: redis://{{ include "housewatch.fullname" . }}-redis:6379
          - name: CLICKHOUSE_HOST
            value: "{{ .Values.clickhouse.host }}"
          - name: CLICKHOUSE_DATABASE
            value: "{{ .Values.clickhouse.database }}"
          - name: CLICKHOUSE_USER
            value: "{{ .Values.clickhouse.user }}"
          - name: CLICKHOUSE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.clickhouse.secretName }}"
                key: "{{ .Values.clickhouse.secretPasswordKey }}"
          - name: CLICKHOUSE_CLUSTER
            value: "{{ .Values.clickhouse.cluster }}"
          - name: CLICKHOUSE_SECURE
            value: "{{ .Values.clickhouse.secure }}"
          - name: CLICKHOUSE_VERIFY
            value: "{{ .Values.clickhouse.verify }}"
          - name: CLICKHOUSE_CA
            value: "{{ .Values.clickhouse.ca }}"
          - name: DATABASE_URL
            value: "{{ . | tpl .Values.database_url }}"
          - name: RABBITMQ_URL
            value: "amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@{{ .Release.Name }}-rabbitmq:5672/" 
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
