apiVersion: v1
kind: Service
metadata:
  name: {{ include "housewatch.fullname" . }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  labels:
    {{- include "housewatch.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "housewatch.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/service: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "housewatch.fullname" . }}-api
  labels:
    {{- include "housewatch.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "housewatch.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/service: web
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "housewatch.fullname" . }}-redis
  labels:
    {{- include "housewatch.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    {{- include "housewatch.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/service: redis
