FROM node:20.4.0-alpine

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

WORKDIR /frontend

COPY . .

RUN pnpm i

VOLUME /frontend/src

CMD ["pnpm", "vite", "--port", "3000", "--host"]
