# Generated by Django 4.1.1 on 2023-03-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewatch', '0004_asyncmigration_last_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='asyncmigration',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
