# Generated by Django 4.1.1 on 2023-05-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housewatch", "0005_asyncmigration_finished_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedQuery",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("query", models.CharField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
