# Generated by Django 4.1.1 on 2023-08-17 01:06

from django.db import migrations, models
import django.db.models.deletion
import housewatch.utils.encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('housewatch', '0006_savedquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledBackup',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('schedule', models.CharField(max_length=255)),
                ('table', models.CharField(max_length=255, null=True)),
                ('database', models.CharField(max_length=255)),
                ('bucket', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('aws_access_key_id', housewatch.utils.encrypted_fields.fields.EncryptedCharField(max_length=255, null=True)),
                ('aws_secret_access_key', housewatch.utils.encrypted_fields.fields.EncryptedCharField(max_length=255, null=True)),
                ('aws_region', housewatch.utils.encrypted_fields.fields.EncryptedCharField(max_length=255, null=True)),
                ('aws_endpoint_url', housewatch.utils.encrypted_fields.fields.EncryptedCharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledBackupRun',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('success', models.BooleanField(default=False)),
                ('error', models.TextField(null=True)),
                ('scheduled_backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housewatch.scheduledbackup')),
            ],
        ),
    ]
