# Generated by Django 4.1.1 on 2023-08-19 00:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('housewatch', '0007_scheduledbackup_scheduledbackuprun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledbackup',
            name='aws_endpoint_url',
        ),
        migrations.RemoveField(
            model_name='scheduledbackup',
            name='aws_region',
        ),
        migrations.AddField(
            model_name='scheduledbackup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledbackup',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledbackup',
            name='last_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housewatch.scheduledbackuprun'),
        ),
        migrations.AddField(
            model_name='scheduledbackup',
            name='last_run_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='scheduledbackuprun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
