# Generated by Django 4.1.1 on 2023-08-24 01:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('housewatch', '0008_remove_scheduledbackup_aws_endpoint_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledbackup',
            name='cluster',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledbackup',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
