# Generated by Django 4.1.1 on 2023-09-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewatch', '0009_scheduledbackup_cluster_alter_scheduledbackup_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledbackup',
            name='incremental_schedule',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduledbackup',
            name='last_base_backup',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduledbackup',
            name='last_incremental_run_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='scheduledbackuprun',
            name='base_backup',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduledbackuprun',
            name='is_incremental',
            field=models.BooleanField(default=False),
        ),
    ]
