# Generated by Django 4.1.1 on 2023-09-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewatch', '0010_scheduledbackup_incremental_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledbackup',
            name='table',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
