# Generated by Django 4.1.1 on 2024-05-29 16:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('housewatch', '0011_scheduledbackup_is_sharded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredReplica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.CharField(max_length=255)),
                ('replica', models.CharField(max_length=255)),
            ],
        ),
    ]
